### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Ostaer** [softdevstory/node-apidoc-markdown#10]
Hello, I have got an error,

apidoc-markdown2 -p test  -o api.rd
```
undefined:25
  throw err;
  ^

TypeError: ejs:37
    35| <% }); //forech parameter -%>
    36| <% } //if parameters -%>
 >> 37|
    38| <% if (data[group][sub][0].header && data[group][sub][0].header.examples && data[group][sub][0].header.examples.length) { -%>
    39|
    40| ### Header Examples

Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at eval (eval at exports.compile (C:\Users\name\AppData\Roaming\npm\node_modules\apidoc-markdown2\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:34:116)
    at Array.forEach (<anonymous>)
    at eval (eval at exports.compile (C:\Users\name\AppData\Roaming\npm\node_modules\apidoc-markdown2\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:958)
    at Array.forEach (<anonymous>)
    at eval (eval at exports.compile (C:\Users\name\AppData\Roaming\npm\node_modules\apidoc-markdown2\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:30:833)
    at eval (eval at exports.compile (C:\Users\name\AppData\Roaming\npm\node_modules\apidoc-markdown2\node_modules\ejs\lib\ejs.js:237:14), <anonymous>:48:19)
    at C:\Users\name\AppData\Roaming\npm\node_modules\apidoc-markdown2\node_modules\ejs\lib\ejs.js:250:15
    at Object.<anonymous> (C:\Users\name\AppData\Roaming\npm\node_modules\apidoc-markdown2\index.js:88:31)
    at Module._compile (module.js:643:30)
```

**Comment by softdevstory** [comment]
Could you attach test data?

**Comment by Ostaer** [comment]
@softdevstory 
Thanks for you replay, The following is the test apidoc data, it will throw that error,

[test.zip](https://github.com/softdevstory/node-apidoc-markdown/files/1684905/test.zip)
